name: CI

on: [push, pull_request]

jobs:
  apple:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Swift Package Manager
        run: swift build
      - name: Test on iPhone 14
        run: xcodebuild -project 'YogaKit.xcodeproj' -scheme 'YogaKit' -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' clean test
      - name: Test on iPhone 14 Pro Max
        run: xcodebuild -project 'YogaKit.xcodeproj' -scheme 'YogaKit' -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max' clean test
      - name: Test on macOS
        run: xcodebuild -project 'YogaKit.xcodeproj' -scheme 'YogaKit' -configuration Debug -sdk macosx -arch x86_64 -arch arm64 clean test
